// C:\Users\Usuario\Projects\convergo\lib\engines\wpArticleEngine.ts
type Role = "user" | "assistant";

type Msg = {
  role: Role;
  content: string;
  createdAt: Date;
};

function must(name: string) {
  const v = process.env[name];
  if (!v) throw new Error(`${name} is missing`);
  return v;
}

function escapeHtml(s: string) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function buildTranscript(messages: Msg[]) {
  return messages
    .map((m) => `${m.role.toUpperCase()}: ${m.content}`)
    .join("\n\n");
}

async function wpCreateDraft(title: string, contentHtml: string) {
  const base = must("WP_BASE_URL").replace(/\/$/, "");
  const username = must("WP_USERNAME");
  const appPassword = must("WP_APP_PASSWORD");

  const auth = Buffer.from(`${username}:${appPassword}`).toString("base64");

  const r = await fetch(`${base}/wp-json/wp/v2/posts`, {
    method: "POST",
    headers: {
      Authorization: `Basic ${auth}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      title,
      content: contentHtml,
      status: "draft",
    }),
  });

  const text = await r.text();
  if (!r.ok) throw new Error(`WP error ${r.status}: ${text}`);

  const data = JSON.parse(text) as { id: number; link?: string };
  return data;
}

export async function createWpArticleDraftFromSession(args: {
  site: string;
  startedAt: Date;
  messages: Msg[];
}) {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) throw new Error("OPENAI_API_KEY is missing");

  const transcript = buildTranscript(args.messages);

  const system = `
You convert a human+AI session transcript into a WordPress draft article.
Output MUST be valid JSON only (no markdown fences, no extra text).
Use simple WordPress-friendly HTML in body_html: <p>, <h2>, <ul>, <li>, <strong>, <em>.
Keep it concise and readable.
`.trim();

  const user = `
Create a draft article from this session.

Return JSON with exactly:
{
  "title": "...",
  "body_html": "...",
  "excerpt": "..."
}

Session transcript:
${transcript}
`.trim();

  const r = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "gpt-5.2",
      messages: [
        { role: "system", content: system },
        { role: "user", content: user },
      ],
    }),
  });

  const rawText = await r.text();
  if (!r.ok) throw new Error(`OpenAI error ${r.status}: ${rawText}`);

  const data = JSON.parse(rawText) as any;
  const content = data?.choices?.[0]?.message?.content?.trim() ?? "";

  let parsed: { title: string; body_html: string; excerpt: string };
  try {
    parsed = JSON.parse(content);
  } catch {
    // fail-soft: wrap the raw model output so we still get something into WP
    const safe = escapeHtml(content).replace(/\n/g, "<br/>");
    parsed = {
      title: `ConVergo Article Draft — ${args.site}`,
      body_html: `<p><em>AI returned non-JSON output. Raw:</em></p><p>${safe}</p>`,
      excerpt: "Draft generated by ConVergo (needs review).",
    };
  }

  const title = (parsed.title || `ConVergo Article Draft — ${args.site}`).trim();
  const bodyHtml = (parsed.body_html || "").trim();
  const excerpt = (parsed.excerpt || "").trim();

  // Put excerpt at top as a subtle lead (WP can ignore excerpt unless theme uses it)
  const finalHtml =
    (excerpt ? `<p><em>${escapeHtml(excerpt)}</em></p>` : "") + bodyHtml;

  return wpCreateDraft(title, finalHtml);
}
