// C:\Users\Usuario\Projects\convergo\lib\engines\wpDraftEngine.ts
type Role = "user" | "assistant";

type Msg = {
  role: Role;
  content: string;
  createdAt: Date;
};

function must(name: string) {
  const v = process.env[name];
  if (!v) throw new Error(`${name} is missing`);
  return v;
}

// Basic WordPress REST create-post (draft)
async function wpCreateDraft(title: string, contentHtml: string) {
  const base = must("WP_BASE_URL").replace(/\/$/, "");
  const username = must("WP_USERNAME");
  const appPassword = must("WP_APP_PASSWORD");

  const auth = Buffer.from(`${username}:${appPassword}`).toString("base64");

  const r = await fetch(`${base}/wp-json/wp/v2/posts`, {
    method: "POST",
    headers: {
      Authorization: `Basic ${auth}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      title,
      content: contentHtml,
      status: "draft",
    }),
  });

  const text = await r.text();
  if (!r.ok) throw new Error(`WP error ${r.status}: ${text}`);

  const data = JSON.parse(text) as { id: number; link?: string };
  return data;
}

function escapeHtml(s: string) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function toTitle(site: string, startedAt: Date) {
  const d = startedAt.toISOString().slice(0, 10);
  return `ConVergo Draft — ${site} — ${d}`;
}

function toHtml(messages: Msg[]) {
  // MVP: clean chronological transcript, lightly formatted
  const blocks = messages.map((m) => {
    const who = m.role === "user" ? "Human" : "AI";
    const time = new Date(m.createdAt).toISOString();
    return `
      <p><strong>${who}</strong> <em style="color:#666">(${escapeHtml(time)})</em></p>
      <p>${escapeHtml(m.content).replace(/\n/g, "<br/>")}</p>
      <hr/>
    `;
  });

  return `
    <div>
      <p><em>Draft generated by ConVergo. Review before publishing.</em></p>
      ${blocks.join("\n")}
    </div>
  `;
}

export async function createWpDraftFromSession(args: {
  site: string;
  startedAt: Date;
  messages: Msg[];
}) {
  const title = toTitle(args.site, args.startedAt);
  const html = toHtml(args.messages);
  return wpCreateDraft(title, html);
}
